# Generated by Django 5.0.4 on 2024-05-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='abstract',
            field=models.TextField(blank=True),
        ),
    ]
