# Generated by Django 5.0.4 on 2024-05-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_books_comment_count_books_score_count_comment_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='books',
            name='score_count',
        ),
    ]
