# Generated by Django 5.0.4 on 2024-05-01 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_remove_books_comment_count_remove_books_score_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='rate_number',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
